### ISSUE TITLE
Establish proper edge id - now in allEdgesLoad

### ISSUE THREAD

**Issue by F-I-D-O** [agents4its/agentpolis#22]

**Comment by F-I-D-O** [comment]
- add new id to SimulationEdge
- pattern in OsmUtil:88

**Comment by zdebou** [comment]
The following string pattern "{fromNodeId}-{toNodeId}" was established and is generated inside SimulationEdgeBuilder.build(fromNodeId, toNodeId). To retrieve uniqueID: SimulationEdge.getUniqueID() and will return String, e.g. "0-1".
