### ISSUE TITLE
Discover where the bug with laneCounts = 1 came from

### ISSUE THREAD

**Issue by F-I-D-O** [agents4its/agentpolis#23]

**Comment by F-I-D-O** [comment]
ComplexGraphBuilder

**Comment by zdebou** [comment]
Extract way tag (cz.agents.gtdgraphimporter.osm.WayTagExtractor.java) + http://wiki.openstreetmap.org/wiki/Lanes

**Comment by zdebou** [comment]
In cz.agents.agentpolis.simmodel.environment.model.citymodel.transportnetwork.elements.SimulationEdge.java

method:
        private void initLaneCounts(Set<ModeOfTransport> permittedModes) {
            permittedModes.stream().forEach(
                    modeOfTransport -> addLaneCount(ModeOfTransportToGraphTypeConverter.convert(modeOfTransport), 1));
        }

and

        public SimulationEdgeBuilder addLaneCount(GraphType type, int laneCount) {
            laneCounts.put(type, laneCount);
            return this;
        }

So it´s permanently set. It wil need edit of the gtdgraphimporter and SimulationEdge

**Comment by zdebou** [comment]
#30
