### ISSUE TITLE
Inconsistent simulation speed

### ISSUE THREAD

**Issue by F-I-D-O** [agents4its/agentpolis#8]
When the simulation is speeded up greatly, the speed indicator no longer corresponds to the simulation speed.

**Comment by schaemar** [comment]
it should be an issue of the agentpolis, it somehow redefines the meaning of simulation speed 1.0x - it runs faster then 1sim.min/sec, see Simulation control layer to see how the simulation speed is being changed and where and how the agentpolis is made to run faster.

**Comment by F-I-D-O** [comment]
This was caused by wrong implementation of wait in Alite, now solved locally
